---
- hosts: Kubernetes
  user: root
  tasks:
  - name: deploy cafeapp on kubernetes
    command: kubectl apply -f cafeapp-deploy.yaml
      
  - name: create service for cafeapp
    command: kubectl apply -f cafeapp-service.yaml
    args:
     chdir: /opt/docker/

  - name: update deployment with new pods if image is updated in dockerhub
    command: kubectl rollout restart deployment.apps/cafe-app