apiVersion: v1
kind: Service
metadata:
  name: cafeAapp-service
  labels: 
    app: cafe-app
spec:
  selector:
    app: cafe-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer